// Generated by https://quicktype.io

namespace AzDevOpsWiReader.Shared
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AuthedUserResponse
    {
        [JsonProperty("descriptor")]
        public string Descriptor { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("mail")]
        public string Mail { get; set; }

        [JsonProperty("unconfirmedMail")]
        public object UnconfirmedMail { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        [JsonProperty("lastModified")]
        public DateTimeOffset LastModified { get; set; }

        [JsonProperty("revision")]
        public long Revision { get; set; }
    }

    public partial class AuthedUserResponse
    {
        public static AuthedUserResponse FromJson(string json) => JsonConvert.DeserializeObject<AuthedUserResponse>(json, AuthedUserResponseConverter.Settings);
    }

    public static class AuthedUserResponseSerialize
    {
        public static string ToJson(this AuthedUserResponse self) => JsonConvert.SerializeObject(self, AuthedUserResponseConverter.Settings);
    }

    internal static class AuthedUserResponseConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
