// Generated by https://quicktype.io

namespace AzDevOpsWiReader.Shared
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GraphGroupMembershipList
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("value")]
        public GraphGroupMembership[] GraphGroupMemberships { get; set; }
    }

    public partial class GraphGroupMembership
    {
        [JsonProperty("containerDescriptor")]
        public string ContainerDescriptor { get; set; }

        [JsonProperty("memberDescriptor")]
        public string MemberDescriptor { get; set; }

        [JsonProperty("_links")]
        public Links Links { get; set; }
    }

    public partial class Links
    {
        [JsonProperty("member")]
        public Container Member { get; set; }

        [JsonProperty("container")]
        public Container Container { get; set; }
    }

    public partial class Container
    {
        [JsonProperty("href")]
        public Uri Href { get; set; }
    }

    public partial class GraphGroupMembership
    {
        public static GraphGroupMembership FromJson(string json) => JsonConvert.DeserializeObject<GraphGroupMembership>(json, GraphGroupMembershipConverter.Settings);
    }

    public static class GraphGroupMembershipSerialize
    {
        public static string ToJson(this GraphGroupMembership self) => JsonConvert.SerializeObject(self, GraphGroupMembershipConverter.Settings);
    }

    internal static class GraphGroupMembershipConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
