// Generated by https://quicktype.io

namespace AzDevOpsWiReader.Shared
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Pricing
    {
        [JsonProperty("tiers")]
        public Tier[] Tiers { get; set; }

        [JsonProperty("offers")]
        public Offers Offers { get; set; }

        [JsonProperty("graduatedOffers")]
        public GraduatedOffers GraduatedOffers { get; set; }

        [JsonProperty("regions")]
        public object[] Regions { get; set; }

        [JsonProperty("discounts")]
        public object[] Discounts { get; set; }

        [JsonProperty("resources")]
        public Dictionary<string, string> Resources { get; set; }

        [JsonProperty("schema")]
        public Schema Schema { get; set; }
    }

    public partial class GraduatedOffers
    {
        [JsonProperty("enterprise-annual")]
        public EnterpriseAnnual EnterpriseAnnual { get; set; }

        [JsonProperty("enterprise-monthly")]
        public EnterpriseAnnual EnterpriseMonthly { get; set; }

        [JsonProperty("package-management")]
        public EnterpriseAnnual PackageManagement { get; set; }

        [JsonProperty("professional-annual")]
        public EnterpriseAnnual ProfessionalAnnual { get; set; }

        [JsonProperty("professional-monthly")]
        public EnterpriseAnnual ProfessionalMonthly { get; set; }

        [JsonProperty("shared-resources-load-testing")]
        public EnterpriseAnnual SharedResourcesLoadTesting { get; set; }

        [JsonProperty("user-plan-basic")]
        public EnterpriseAnnual UserPlanBasic { get; set; }
    }

    public partial class EnterpriseAnnual
    {
        [JsonProperty("global")]
        public EnterpriseAnnualGlobal Global { get; set; }
    }

    public partial class EnterpriseAnnualGlobal
    {
        [JsonProperty("prices")]
        public Price[] Prices { get; set; }

        [JsonProperty("pricingTypes")]
        public string PricingTypes { get; set; }
    }

    public partial class Price
    {
        [JsonProperty("limit")]
        public double Limit { get; set; }

        [JsonProperty("price")]
        public PriceClass PricePrice { get; set; }
    }

    public partial class PriceClass
    {
        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public partial class Offers
    {
        [JsonProperty("shared-resources-build-deployment-hosted")]
        public SharedResourcesBuildDeploymentHosted SharedResourcesBuildDeploymentHosted { get; set; }

        [JsonProperty("shared-resources-build-deployment-private")]
        public SharedResourcesBuildDeploymentHosted SharedResourcesBuildDeploymentPrivate { get; set; }

        [JsonProperty("test-manager")]
        public SharedResourcesBuildDeploymentHosted TestManager { get; set; }
    }

    public partial class SharedResourcesBuildDeploymentHosted
    {
        [JsonProperty("prices")]
        public Prices Prices { get; set; }

        [JsonProperty("pricingTypes")]
        public string PricingTypes { get; set; }
    }

    public partial class Prices
    {
        [JsonProperty("global")]
        public PriceClass Global { get; set; }
    }

    public partial class Schema
    {
        [JsonProperty("serviceSlug")]
        public string ServiceSlug { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("devOpsUsers")]
        public long DevOpsUsers { get; set; }

        [JsonProperty("artifacts")]
        public long Artifacts { get; set; }

        [JsonProperty("artifactUnits")]
        public long ArtifactUnits { get; set; }

        [JsonProperty("vums")]
        public long Vums { get; set; }

        [JsonProperty("hostedAgents")]
        public long HostedAgents { get; set; }

        [JsonProperty("privateAgents")]
        public long PrivateAgents { get; set; }

        [JsonProperty("test")]
        public long Test { get; set; }

        [JsonProperty("tier")]
        public string Tier { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("isCollapsed")]
        public bool IsCollapsed { get; set; }

        [JsonProperty("isBreakingChange")]
        public bool IsBreakingChange { get; set; }

        [JsonProperty("upfrontTotal")]
        public double UpfrontTotal { get; set; }

        [JsonProperty("total")]
        public double Total { get; set; }
    }

    public partial class Tier
    {
        [JsonProperty("slug")]
        public string Slug { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
    }

    public partial class Pricing
    {
        public static Pricing FromJson(string json) => JsonConvert.DeserializeObject<Pricing>(json, PricingConverter.Settings);
    }

    public static class PricingSerialize
    {
        public static string ToJson(this Pricing self) => JsonConvert.SerializeObject(self, PricingConverter.Settings);
    }

    internal static class PricingConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
